name: logs_repository
description: A repository that handles logs related requests.
version: 1.0.0+1
publish_to: none


environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  logs_api:
    path: ../logs_api

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
