name: logs_api
description: The interface and models for an API providing access to logs.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.1.3

dependencies:
  equatable: ^2.0.5
  uuid: ^4.2.1

dev_dependencies:
  lints: ^2.0.0