name: local_storage_logs_api
description: A Flutter implementation of the LogsApi that uses local storage.
version: 1.0.0+1
publish_to: none


environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
 logs_api:
    path: ../logs_api
 rxdart: ^0.27.7
 shared_preferences: ^2.2.2

dev_dependencies:
  lints: ^2.0.0
